# Generated by Django 4.0 on 2021-12-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDB',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField()),
                ('sample_id', models.IntegerField()),
                ('n_butyric_acid', models.FloatField()),
                ('n_valeric_acid', models.FloatField()),
                ('n_caproic_acid', models.FloatField()),
                ('n_heptanoic_acid', models.FloatField()),
                ('n_caprylic_acid', models.FloatField()),
            ],
            options={
                'db_table': 'metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MMonitorDB',
            fields=[
                ('read_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField()),
                ('sample_id', models.IntegerField()),
                ('taxonomy', models.TextField()),
                ('abundance', models.IntegerField()),
            ],
            options={
                'db_table': 'mmonitor',
                'managed': False,
            },
        ),
    ]
