# Generated by Django 5.1.1 on 2025-02-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDB',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField()),
                ('sample_id', models.IntegerField()),
                ('n_butyric_acid', models.FloatField()),
                ('n_valeric_acid', models.FloatField()),
                ('n_caproic_acid', models.FloatField()),
                ('n_heptanoic_acid', models.FloatField()),
                ('n_caprylic_acid', models.FloatField()),
            ],
            options={
                'db_table': 'metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MMonitorDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_mmonitordb',
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_count', models.IntegerField(default=0)),
                ('trna_count', models.IntegerField(default=0)),
                ('rrna_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_annotation', to='users.mag')),
            ],
            options={
                'db_table': 'dashboard_annotation',
            },
        ),
        # Add SQL operation for SQLite-specific table creation
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS dashboard_annotation (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                gene_count INTEGER NOT NULL DEFAULT 0,
                trna_count INTEGER NOT NULL DEFAULT 0,
                rrna_count INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                mag_id INTEGER NOT NULL,
                FOREIGN KEY (mag_id) REFERENCES users_mag (id) ON DELETE CASCADE
            );
            """,
            "DROP TABLE IF EXISTS dashboard_annotation;"
        ),
    ]
