# Generated by Django 5.1.1 on 2025-02-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS `dashboard_annotation` (
                `id` INT AUTO_INCREMENT PRIMARY KEY,
                `gene_count` INTEGER NOT NULL DEFAULT 0,
                `trna_count` INTEGER NOT NULL DEFAULT 0,
                `rrna_count` INTEGER NOT NULL DEFAULT 0,
                `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                `mag_id` INTEGER NOT NULL,
                FOREIGN KEY (`mag_id`) REFERENCES `users_mag` (`id`) ON DELETE CASCADE
            );
            """,
            "DROP TABLE IF EXISTS dashboard_annotation;"
        ),
    ]
