# Generated by Django 5.1.1 on 2025-02-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20250226_1037'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS dashboard_annotation (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                gene_count INTEGER NOT NULL DEFAULT 0,
                trna_count INTEGER NOT NULL DEFAULT 0,
                rrna_count INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                mag_id INTEGER NOT NULL,
                FOREIGN KEY (mag_id) REFERENCES users_mag (id) ON DELETE CASCADE
            );
            """,
            "DROP TABLE IF EXISTS dashboard_annotation;"
        ),
    ] 