# Generated by Django 5.1.1 on 2025-02-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('dashboard', '0003_create_annotation_sqlite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationBackup',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('gene_count', models.IntegerField(default=0)),
                ('trna_count', models.IntegerField(default=0)),
                ('rrna_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_annotation_backup', to='users.mag')),
            ],
            options={
                'db_table': 'dashboard_annotation',
            },
        ),
    ] 