# Generated by Django 5.1.1 on 2025-02-26 11:20

from django.db import migrations, connections


def create_annotation_table(apps, schema_editor):
    # Only run for SQLite
    if connections['default'].vendor == 'sqlite':
        with connections['default'].cursor() as cursor:
            cursor.execute("""
            CREATE TABLE IF NOT EXISTS dashboard_annotation (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                gene_count INTEGER NOT NULL DEFAULT 0,
                trna_count INTEGER NOT NULL DEFAULT 0,
                rrna_count INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                mag_id INTEGER NOT NULL,
                FOREIGN KEY (mag_id) REFERENCES users_mag (id) ON DELETE CASCADE
            );
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_create_annotation_models'),
    ]

    operations = [
        migrations.RunPython(create_annotation_table),
    ] 