# Generated by Django 4.2.9 on 2025-03-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_ensure_sqlite_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnotationBackup',
        ),
    ]
