# Generated by Django 4.2.9 on 2025-03-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_annotationbackup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='mag',
        ),
        migrations.DeleteModel(
            name='MMonitorDB',
        ),
        migrations.DeleteModel(
            name='MetaDB',
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
    ]
