# Generated by Django 5.1.1 on 2024-12-28 13:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('sample_id', models.CharField(default='empty', max_length=255)),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Metadata',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('taxonomy', models.CharField(max_length=255)),
                ('sample_name', models.CharField(max_length=255)),
                ('gff_file', models.TextField(default='empty')),
                ('fasta_file', models.TextField(default='empty')),
                ('fai_file', models.TextField(default='empty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completeness', models.FloatField(blank=True, null=True)),
                ('contamination', models.FloatField(blank=True, null=True)),
                ('strain_heterogeneity', models.FloatField(blank=True, null=True)),
                ('gene_count', models.IntegerField(blank=True, null=True)),
                ('trna_count', models.IntegerField(blank=True, null=True)),
                ('rrna_count', models.IntegerField(blank=True, null=True)),
                ('cds_count', models.IntegerField(blank=True, null=True)),
                ('annotation_summary', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeggMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kegg_maps', to='users.mag')),
            ],
        ),
        migrations.CreateModel(
            name='NanoporeRecord',
            fields=[
                ('read_id', models.AutoField(primary_key=True, serialize=False)),
                ('taxonomy', models.TextField(default='empty')),
                ('abundance', models.FloatField(default=0.0)),
                ('count', models.FloatField(default=0.0)),
                ('sample_id', models.CharField(default='empty', max_length=255)),
                ('project_id', models.CharField(default='empty', max_length=255)),
                ('subproject', models.CharField(default='empty', max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('tax_id', models.IntegerField(default=0)),
                ('tax_genus', models.CharField(blank=True, default='empty', max_length=255, null=True)),
                ('tax_family', models.CharField(blank=True, default='empty', max_length=255, null=True)),
                ('tax_order', models.CharField(blank=True, default='empty', max_length=255, null=True)),
                ('tax_class', models.CharField(blank=True, default='empty', max_length=255, null=True)),
                ('tax_phylum', models.CharField(blank=True, default='empty', max_length=255, null=True)),
                ('tax_superkingdom', models.CharField(blank=True, default='empty', max_length=255, null=True)),
                ('tax_clade', models.CharField(blank=True, default='empty', max_length=255, null=True)),
                ('tax_subspecies', models.CharField(blank=True, default='empty', max_length=255, null=True)),
                ('tax_species_subgroup', models.CharField(blank=True, default='empty', max_length=255, null=True)),
                ('tax_species_group', models.CharField(blank=True, default='empty', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SequencingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=255)),
                ('subproject_id', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('mean_read_length', models.FloatField(blank=True, null=True)),
                ('median_read_length', models.FloatField(blank=True, null=True)),
                ('mean_quality_score', models.FloatField(blank=True, null=True)),
                ('mean_gc_content', models.FloatField(blank=True, null=True)),
                ('read_lengths', models.TextField(blank=True, null=True)),
                ('avg_qualities', models.TextField(blank=True, null=True)),
                ('number_of_reads', models.IntegerField(blank=True, null=True)),
                ('total_bases_sequenced', models.IntegerField(blank=True, null=True)),
                ('q20_score', models.FloatField(blank=True, null=True)),
                ('q30_score', models.FloatField(blank=True, null=True)),
                ('avg_quality_per_read', models.TextField(blank=True, null=True)),
                ('base_quality_avg', models.TextField(blank=True, null=True)),
                ('gc_contents_per_sequence', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sequencing Statistics',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_field', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
