# Generated by Django 5.1.1 on 2025-02-26 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mag',
            name='annotations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mag',
            name='protein_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mag',
            name='quality_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mag',
            name='fai_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mag',
            name='fasta_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mag',
            name='gff_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mag',
            name='sample_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mag',
            name='taxonomy',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mag',
            unique_together={('name', 'user')},
        ),
        migrations.DeleteModel(
            name='KeggMap',
        ),
    ]
