# Generated by Django 4.2.9 on 2025-03-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mag_annotations_mag_protein_file_mag_quality_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mag',
            name='annotations',
        ),
        migrations.AddField(
            model_name='mag',
            name='annotations_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MAGAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=255)),
                ('contig', models.CharField(max_length=255)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('strand', models.CharField(max_length=1)),
                ('product', models.CharField(max_length=1000)),
                ('kegg', models.CharField(blank=True, max_length=255, null=True)),
                ('ec_numbers', models.JSONField(default=list)),
                ('uniref', models.JSONField(default=list)),
                ('sequence_nt', models.TextField()),
                ('sequence_aa', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mag_annotations', to='users.mag')),
            ],
            options={
                'indexes': [models.Index(fields=['sample', 'gene_id'], name='users_magan_sample__225670_idx'), models.Index(fields=['contig'], name='users_magan_contig_f04386_idx')],
            },
        ),
    ]
