name: MMonitor pipeline complete build ubuntu

on:
  push:
    branches:
      - workflows
  pull_request:
    branches:
      - workflows
  workflow_dispatch:

jobs:
  build-flye:
    name: Build Flye from Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Flye
        run: |
          git clone https://github.com/fenderglass/Flye.git desktop/lib/Flye
          cd desktop/lib/Flye
          python3 setup.py build
          python3 setup.py install --user
      - name: Upload Flye binaries
        uses: actions/upload-artifact@v4
        with:
          name: flye-binaries
          path: ~/.local/bin/flye

  build-samtools:
    name: Build Samtools from Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build HTSlib
        run: |
          git clone --recursive https://github.com/samtools/htslib.git
          cd htslib
          git submodule update --init --recursive
          autoheader
          autoconf
          autoreconf -i
          ./configure
          make
          sudo make install
      - name: Build Samtools
        run: |
          git clone https://github.com/samtools/samtools.git
          cd samtools
          autoreconf -i
          ./configure
          make
          sudo make install
      - name: Upload Samtools binaries
        uses: actions/upload-artifact@v4
        with:
          name: samtools-binaries
          path: /usr/local/bin/samtools

  build-centrifuger:
    name: Build Centrifuger from Source on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential
  
      - name: Clone Centrifuger
        run: git clone https://github.com/mourisl/centrifuger.git
  
      - name: Build Centrifuger
        run: |
          cd centrifuger
          make
  
      - name: Upload Centrifuger binaries
        uses: actions/upload-artifact@v4
        with:
          name: centrifuger-binaries
          path: centrifuger/centrifuger

  build-keggcharter:
    name: Prepare KEGGCharter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Clone KEGGCharter
        run: |
          git clone https://github.com/iquasere/KEGGCharter.git
      
      - name: Upload KEGGCharter files
        uses: actions/upload-artifact@v4
        with:
          name: keggcharter-files
          path: KEGGCharter

  build-bakta:
    name: Build Bakta from Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Build Bakta
        run: |
          git clone https://github.com/oschwengers/bakta.git
          cd bakta
          pip install .
      
      - name: Find Bakta files
        run: |
          which bakta
          ls -l $(which bakta)
          find /opt/hostedtoolcache/Python -name "bakta*"
      
      - name: Upload Bakta files
        uses: actions/upload-artifact@v4
        with:
          name: bakta-files
          path: |
            /opt/hostedtoolcache/Python/3.10.15/x64/bin/bakta
            /opt/hostedtoolcache/Python/3.10.15/x64/bin/bakta-*

  build-emu:
    name: Clone EMU 16S Profiler (excluding large files)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Clone EMU (sparse checkout)
        run: |
          mkdir emu
          cd emu
          git init
          git remote add origin https://github.com/treangenlab/emu.git
          git config core.sparseCheckout true
          echo '/*' > .git/info/sparse-checkout
          echo '!emu_database' >> .git/info/sparse-checkout
          echo '!example' >> .git/info/sparse-checkout
          echo '!example_customdb' >> .git/info/sparse-checkout
          git pull origin main
      
      - name: Upload EMU files
        uses: actions/upload-artifact@v4
        with:
          name: emu-files
          path: |
            emu
            !emu/emu_database
            !emu/example
            !emu/example_customdb

  build-medaka:
    name: Build Medaka from Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Use Python 3.10 for compatibility
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev zlib1g-dev
      
      - name: Build Medaka
        run: |
          python3 -m venv medaka-env
          source medaka-env/bin/activate
          pip install medaka
          
        
          
          
          
          
          

      
      - name: Upload Medaka files
        uses: actions/upload-artifact@v4
        with:
          name: medaka-files
          path: |
            ~/.local/bin/medaka
            ~/.local/bin/medaka_*

  build-metabat2:
    name: Build MetaBAT2 from Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-all-dev
      
      - name: Build MetaBAT2
        run: |
          git clone https://bitbucket.org/berkeleylab/metabat.git
          cd metabat
          mkdir build && cd build
          cmake ..
          make
      
      - name: Upload MetaBAT2 binary
        uses: actions/upload-artifact@v4
        with:
          name: metabat2-binary
          path: metabat/build/bin/metabat2


  build-mmonitor-pyinstaller:
    name: Build MMonitor with PyInstaller
    runs-on: ubuntu-latest
    needs: [build-flye, build-samtools, build-centrifuger, build-keggcharter, build-bakta, build-emu, build-medaka, build-metabat2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Install Python dependencies
        run: |
          python3 -m venv pyinstaller-env
          source pyinstaller-env/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Prepare binaries and scripts
        run: |
          mkdir -p $GITHUB_WORKSPACE/desktop/src/mmonitor/bin
          mkdir -p $GITHUB_WORKSPACE/desktop/src/mmonitor/emu
          mkdir -p $GITHUB_WORKSPACE/desktop/src/mmonitor/KEGGCharter
          cp artifacts/flye-binaries/flye $GITHUB_WORKSPACE/desktop/src/mmonitor/bin/ || true
          cp artifacts/samtools-binaries/samtools $GITHUB_WORKSPACE/desktop/src/mmonitor/bin/ || true
          cp artifacts/centrifuger-binaries/centrifuger $GITHUB_WORKSPACE/desktop/src/mmonitor/bin/ || true
          cp -r artifacts/keggcharter-files/* $GITHUB_WORKSPACE/desktop/src/mmonitor/KEGGCharter/ || true
          cp artifacts/bakta-files/bakta* $GITHUB_WORKSPACE/desktop/src/mmonitor/bin/ || true
          cp -r artifacts/emu-files/* $GITHUB_WORKSPACE/desktop/src/mmonitor/emu/ || true
          cp artifacts/medaka-files/medaka* $GITHUB_WORKSPACE/desktop/src/mmonitor/bin/ || true
          cp artifacts/metabat2-binary/metabat2 $GITHUB_WORKSPACE/desktop/src/mmonitor/bin/ || true
          chmod +x $GITHUB_WORKSPACE/desktop/src/mmonitor/bin/* || true

      - name: List artifacts and copied files
        run: |
          echo "Artifacts:"
          ls -R artifacts
          echo "Copied files:"
          ls -R $GITHUB_WORKSPACE/desktop/src/mmonitor

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE/desktop:$GITHUB_WORKSPACE/desktop/src:$GITHUB_WORKSPACE/desktop/src/mmonitor" >> $GITHUB_ENV

      - name: Build MMonitor
        run: |
          cd desktop/src/mmonitor
          pyinstaller --onefile --add-data "bin:bin" --add-data "KEGGCharter:KEGGCharter" --add-data "emu:emu" __main__.py --distpath ../../output
          ls -lah ../../output

      - name: Upload MMonitor binary
        uses: actions/upload-artifact@v4
        with:
          name: mmonitor-binary-ubuntu
          path: desktop/output/