name: Build MMonitor for Multiple Platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux-22:
    name: Build MMonitor on Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Flye
        run: |
          git clone https://github.com/fenderglass/Flye.git
          cd Flye
          python3 setup.py build
          python3 setup.py install --user

      - name: Build Samtools
        run: |
          git clone --recursive https://github.com/samtools/htslib.git
          cd htslib
          autoheader && autoconf && autoreconf -i
          ./configure && make && sudo make install
          cd ..
          git clone https://github.com/samtools/samtools.git
          cd samtools
          autoreconf -i && ./configure && make && sudo make install

      - name: Build Centrifuge
        run: |
          git clone https://github.com/DaehwanKimLab/centrifuge.git
          cd centrifuge
          make

      - name: Install PyInstaller
        run: |
          python3 -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build MMonitor
        run: |
          cd desktop/src/mmonitor
          pyinstaller --onefile __main__.py --distpath ./output

      - name: Upload MMonitor binary (Linux - Ubuntu 22)
        uses: actions/upload-artifact@v4
        with:
          name: mmonitor-binary-ubuntu-22
          path: ./output

  build-linux-20:
    name: Build MMonitor on Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Flye
        run: |
          git clone https://github.com/fenderglass/Flye.git
          cd Flye
          python3 setup.py build
          python3 setup.py install --user

      - name: Build Samtools
        run: |
          git clone --recursive https://github.com/samtools/htslib.git
          cd htslib
          autoheader && autoconf && autoreconf -i
          ./configure && make && sudo make install
          cd ..
          git clone https://github.com/samtools/samtools.git
          cd samtools
          autoreconf -i && ./configure && make && sudo make install

      - name: Build Centrifuge
        run: |
          git clone https://github.com/DaehwanKimLab/centrifuge.git
          cd centrifuge
          make

      - name: Install PyInstaller
        run: |
          python3 -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build MMonitor
        run: |
          cd desktop/src/mmonitor
          pyinstaller --onefile __main__.py --distpath ./output

      - name: Upload MMonitor binary (Linux - Ubuntu 20)
        uses: actions/upload-artifact@v4
        with:
          name: mmonitor-binary-ubuntu-20
          path: ./output

  build-debian:
    name: Build MMonitor on Debian
    runs-on: debian:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y python3 python3-pip build-essential zlib1g-dev bzip2 libbz2-dev liblzma-dev libncurses5-dev
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller

      - name: Build Flye
        run: |
          git clone https://github.com/fenderglass/Flye.git
          cd Flye
          python3 setup.py build
          python3 setup.py install --user

      - name: Build Samtools
        run: |
          git clone --recursive https://github.com/samtools/htslib.git
          cd htslib
          autoheader && autoconf && autoreconf -i
          ./configure && make && sudo make install
          cd ..
          git clone https://github.com/samtools/samtools.git
          cd samtools
          autoreconf -i && ./configure && make && sudo make install

      - name: Build Centrifuge
        run: |
          git clone https://github.com/DaehwanKimLab/centrifuge.git
          cd centrifuge
          make

      - name: Build MMonitor
        run: |
          cd desktop/src/mmonitor
          pyinstaller --onefile __main__.py --distpath ./output

      - name: Upload MMonitor binary (Debian)
        uses: actions/upload-artifact@v4
        with:
          name: mmonitor-binary-debian
          path: ./output

  build-macos:
    name: Build MMonitor on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Flye
        run: |
          git clone https://github.com/fenderglass/Flye.git
          cd Flye
          python3 setup.py build
          python3 setup.py install --user

      - name: Build Samtools
        run: |
          brew install samtools

      - name: Build Centrifuge
        run: |
          git clone https://github.com/DaehwanKimLab/centrifuge.git
          cd centrifuge
          make

      - name: Install PyInstaller
        run: |
          python3 -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build MMonitor
        run: |
          cd desktop/src/mmonitor
          pyinstaller --onefile __main__.py --distpath ./output

      - name: Upload MMonitor binary (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: mmonitor-binary-macos
          path: ./output

  build-centos:
    name: Build MMonitor on CentOS 7
    runs-on: centos-7
    container:
      image: centos:7
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          yum install -y python3 python3-pip gcc zlib-devel bzip2-devel xz-devel ncurses-devel
          pip3 install --upgrade pip
          pip3 install pyinstaller

      - name: Build Flye
        run: |
          git clone https://github.com/fenderglass/Flye.git
          cd Flye
          python3 setup.py build
          python3 setup.py install --user

      - name: Build Samtools
        run: |
          git clone --recursive https://github.com/samtools/htslib.git
          cd htslib
          autoheader && autoconf && autoreconf -i
          ./configure && make && sudo make install
          cd ..
          git clone https://github.com/samtools/samtools.git
          cd samtools
          autoreconf -i && ./configure && make && sudo make install

      - name: Build Centrifuge
        run: |
          git clone https://github.com/DaehwanKimLab/centrifuge.git
          cd centrifuge
          make

      - name: Build MMonitor
        run: |
          cd desktop/src/mmonitor
          pyinstaller --onefile __main__.py --distpath ./output

      - name: Upload MMonitor binary (CentOS)
        uses: actions/upload-artifact@v4
        with:
          name: mmonitor-binary-centos
          path: ./output
