name: Build Flye, Centrifuge, Samtools, and Main Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-flye:
    name: Build Flye from Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Flye
        run: |
          # Commands to build Flye
          cd desktop/lib/Flye-2.9.5
          python3 setup.py build
          python3 setup.py install --user
          
      - name: Upload Flye binaries
        uses: actions/upload-artifact@v4
        with:
          name: flye-binaries
          path: ~/.local/bin/flye

  build-samtools:
    name: Build Samtools from Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build HTSlib
        run: |
          # Commands to build HTSlib (dependency for Samtools)
          # Clone HTSlib and its submodule (htscodecs)
          git clone --recursive https://github.com/samtools/htslib.git
          cd htslib
          git submodule update --init --recursive
          # Generate configure script if missing
          autoheader
          autoconf
          autoreconf -i
          # Configure and build HTSlib
          autoreconf -i  # Regenerate configure script for samtools as well
          ./configure
          make
          sudo make install

      - name: Build Samtools
        run: |
          # Commands to build Samtools
          git clone https://github.com/samtools/samtools.git
          cd samtools
          autoreconf -i  # Regenerate configure script for samtools as well
          ./configure
          make
          sudo make install

      - name: Upload Samtools binaries
        uses: actions/upload-artifact@v4
        with:
          name: samtools-binaries
          path: /usr/local/bin/samtools

  build-centrifuge:
    name: Build Centrifuge from Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Centrifuge
        run: |
          # Commands to build Centrifuge
          git clone https://github.com/DaehwanKimLab/centrifuge.git
          cd centrifuge
          make

      - name: Upload Centrifuge binaries
        uses: actions/upload-artifact@v4
        with:
          name: centrifuge-binaries
          path: centrifuge

  build-mmonitor-pyinstaller:
    name: Build MMonitor with PyInstaller
    runs-on: ubuntu-latest
    needs: [build-flye, build-samtools, build-centrifuge]  # Ensure dependencies are built first
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PyInstaller
        run: |
          python3 -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build MMonitor
        run: |
          # Assuming your main script is located in desktop/src/mmonitor/__main__.py
          cd desktop/src/mmonitor
          pyinstaller --onefile __main__.py

      - name: Upload MMonitor binary
        uses: actions/upload-artifact@v4
        with:
          name: mmonitor-binary
          path: dist/__main__

