jobs:
  build-mac:
    name: Build MMonitor for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          python3 -m pip install pyinstaller

      - name: Build MMonitor
        run: |
          cd desktop/src/mmonitor
          pyinstaller --onefile __main__.py --distpath ../../output

      - name: Upload MMonitor binary
        uses: actions/upload-artifact@v4
        with:
          name: mmonitor-binary
          path: desktop/output/
