name: Sync Changelog

on:
  push:
    branches:
      - main
    paths:
      - 'CHANGELOG.md'

jobs:
  sync-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy changelog to other repository
        run: |
          git clone https://github.com/lucast122/mmonitor-server.git
          cp CHANGELOG.md /CHANGELOG.md
          cd mmonitor-other-repo
          git config --local user.email "timolucas1994@gmail.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Sync changelog"
          git push https://lucast122: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@github.com/lucast122/mmonitor-server.git main

